name: Deploy to github page

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 10
        run_install: false

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        cache: 'pnpm'

    - name: Build
      run: |
        pnpm i
        pnpm run build:github

    - name: Upload static files as artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist
      
  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
